name: lint-js
on: [pull_request]

jobs:
  lint-js:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: install modules
        run: yarn install
      - name: lint js
        run: yarn lint